### PR TITLE
Skip bot2-vis gracefully if GTK2+ not found

### PR DESCRIPTION
**Pull request by wxmerkt**
Note, this merges into libbot-openhumanoids since libbot-openhumanoids has not been merged upstream to RL/libbot yet

### CODE REVIEW

**Comment by mauricefallon** [comment]
what prompted this? What's the impact on oh-distro? I don't think it will compile without this.
e.g. it is used in pronto as an alternative to director.

bot2-vis is near/at end-of-life. I'd like to remove it in time.

**Comment by wxmerkt** [comment]
Installation on a headless system as part of valkyrie-lcm-distro. There's no impact on oh-distro or other desktop version users as we all have GTK2 installed. It only impacts headless installations where bot2-vis wouldn't work nonetheless.

I'll add another commit to more gracefully handle follow on conditions (lcmgl-viewer requires bot2-vis)

**Comment by patmarion** [comment]
Please don't merge this.  There is already support for disabling bot2-vis in the top level CMakeLists.txt but it has been disabled in this openhumanoids fork, we should just fix that.

**Comment by iamwolf** [comment]
Happy to get both repositories back aligned and not merge this. 
The ``WITH_BOT_VIS`` and ``USE_BOT_VIS`` do not fully work though. We have ``find_package(bot2-vis)`` statements that do not find the package and do not influence the setting of USE_BOT_VIS. Happy to take another look where you recommend

**Pull request closed without merging**
