### PR TITLE
Fix check for bot vis

### PR DESCRIPTION
**Pull request by patmarion**

### CODE REVIEW

**Comment by patmarion** [comment]
I think this fixes the headless build without interfering with regular builds.

It checks for the existence of the gdkx header to determine whether gtk+x11 is installed.  Then it sets the cmake option USE_BOT_VIS to be on/off depending on whether this header exists.

When USE_BOT_VIS is OFF, the bot2-vis module is skipped, and the bot2-lcmgl and bot2-frames modules are built but the renderers are skipped.

**Comment by patmarion** [comment]
Probably worth testing this before merging :)

**Comment by patmarion** [comment]
@iamwolf just checking whether you saw this one?  no rush, i think the motivation for resolving this is to support the headless build you're working on?

**Comment by mauricefallon** [comment]
BTW @patmarion the commits you made around here:
https://github.com/openhumanoids/libbot/commit/4d58526f342c0d8186b32c9dda2d99ad452ded3e
disable bot-vis (if I remember correctly) incorrectly in linux. 

This was a problem I had when I tried to merge libbot-openhumanoids into RL/libbot master. Russ and I would like to merge it in.

**Comment by patmarion** [comment]
Yep, unfortunately there was just a dumb typo in that commit :(  This PR fixes that typo among other things.  However, that commit is already in RL/libbot.

The main issue you had reverted when you forked RL/libbot to openhumands was a change I had made to how libbot links with libjpeg.  Unfortunately, my fix led to a .pc pkg-config file which is incompatible when read by pods.cmake.  This was OK in drake, since drake never attempts to load the bad .pc file, but openhumanoids does.  So this is a subtle one, which is still outstanding.

**Comment by patmarion** [comment]
that being said, I can help merge all the changes in openhumanoids/libbot _except_ for the libjpeg revert.  The libjpeg fix was required to get libbot to build on mac homebrew.  I could find an alternative fix that plays nicely with pods.cmake.

**Comment by patmarion** [comment]
This is the revert commit that you made in order to fix the openhumanoids build:

https://github.com/openhumanoids/libbot/commit/eb61f9bed5df654ffb0ce47ce44ca3d379a6e6e8

That commit is actually reverting two things. 1) my typo in finding GDX header 2) libjpeg linking.

After this PR, 1) is resolved.  2) remains.  Sorry for the complications!

**Comment by wxmerkt** [comment]
Pat, apologies for the delay in getting back to this issue; thanks for your work. I'm seeing the same compile issue on my Mac as well as on Travis, cf. [here](https://travis-ci.org/openhumanoids/valkyrie-lcm-distro/builds/117167700#L2615).

Is the way I set the CMAKE_CACHE_ARGS wrong? Cf. [here](https://github.com/openhumanoids/valkyrie-lcm-distro/compare/15a0f27e9036%5E...46c111b0faf4)

Thanks :)

**Comment by patmarion** [comment]
Ok, there seem to be two things going on.

Your build error in the travis log was reporting that libbot does not have an install step.  That's because you are building it as a standard cmake project, instead of building it as a pod (when built as a pod, the pod Makefile provides the install step).  I just added a new commit to introduce a dummy install step so that libbot will work when compiled as a regular cmake project.  Try this revision:

2a243a304f687ed95b913d7e69c230cac402e2fb

The other problem is that even though you added -DWITH_BOS_VIS=OFF, I can see in the travis log it says:

Configuring with bot2-vis, modules requiring gtk+x11 will be built.

So somehow that argument didn't get passed in.  Strange.  Maybe try -DWITH_BOT_VIS:BOOL=OFF

**Comment by wxmerkt** [comment]
Thanks, that fixed it (both on Travis as well as on the Mac).

From my standpoint it's ready to merge, thanks so much for fixing this :)

**Pull request merged**
